name: Build and Release

on:
  push:
    branches:
      - build

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate Tag
        id: tagger
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-release:
    needs: tag
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build for MacOS
      run: npm run build:macos

    - name: Build for Windows
      run: npm run build:win

    - name: Build for Linux
      run: npm run build:linux

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/mockingbird-proxy-portable-*.exe
          ./dist/mockingbird-proxy-*.dmg
          ./dist/mockingbird-proxy-*.AppImage
        token: ${{ secrets.GH_TOKEN }}
        tag_name: ${{ needs.tag.outputs.new_tag }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

